[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "xomics"
version = "0.1.0"
description = "Python framework for eXplainable Omics analysis"
authors = [
    "Stephan Breimann <stephanbreimann@gmail.de>",
    "Clarissa Rienaecker <clarissa.rienaecker@web.de>"]
license = "MIT"
readme = "README.rst"

# Add classifiers to provide more details about the package (used by PyPI)
classifiers = [
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Natural Language :: English",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "License :: OSI Approved :: MIT License",
    "Development Status :: 3 - Alpha",
    # 4 - Beta (feature complete, may need minor improvements
    # 5 - Prodcution/Stable (softaware is stable & deployed)
    # 6 - Mature (Stable & in production for long time)
    # 7 - Inactive (project no longer maintained)
]

# Requierements
[tool.poetry.dependencies]
python = ">=3.9,<=3.11"
cycler = "^0.11.0"
et-xmlfile = "^1.1.0"
fonttools = "^4.37.1"
joblib = "^1.1.0"
kiwisolver = "^1.4.4"
matplotlib = "^3.5.3"
numpy = "^1.24.4"
openpyxl = "^3.0.10"
packaging = "^21.3"
pandas = ">=2.0.0, <=2.1"   # Avoid Future warning due to seaborn, Can be increased if seaborn solvded this >12.0
patsy = "^0.5.2"
Pillow = "^9.2.0"
pyparsing = "^3.0.9"
python-dateutil = "^2.8.2"
pytz = "^2022.2.1"
scikit-learn = "^1.1.2"
scipy = "^1.9.0"
seaborn = "^0.11.2"
six = "^1.16.0"
statsmodels = "^0.13.2"
threadpoolctl = "^3.1.0"
pip = "^23.2.01"

#... (keep the other dependencies as they are)
[tool.poetry.dev-dependencies]
sphinx = "5.3.0" #">=5.0,<7.0"
sphinx_rtd_theme = "1.3.0" #"^1.3.0"
#pydata_sphinx_theme = "^0.13.3"
sphinx-design = "0.5" #{ version = "^0.5", python = ">=3.8" }
sphinx_copybutton = "0.5.2" #"^0.5.2"
sphinxext-opengraph = "0.8.2" #"^0.8.2"
sphinx-autodoc-typehints = "1.15.0" #"^1.15.0"
docutils = "0.18.0"
poetry = "1.6.1"
urllib3 = "2.0.4"
nbsphinx = "0.9.3"
nbconvert = "7.8.0"
nbformat = "5.9.2"
ipykernel = "6.25.2"
pandoc = "2.3"
numpydoc = "1.5.0"
pytest = "7.4.2"
pytest-mpl = "0.16.1"
hypothesis = "6.86.2"
black = "22.12.0"

# Optional dependencies
#[tool.poetry.extras]
#plots = ["matplotlib", "seaborn"]

# Project URLs
[tool.poetry.urls]
"Repository" = "https://github.com/breimanntools/xomics"
"Documentation" = "https://xomics.readthedocs.io"

# If you use a tool for linting or formatting, you can add its configurations here.
# For example, if you use `black` for formatting:
[tool.black]
line-length = 88
exclude = '''
/(
    \.git
  | \.venv
  | \.eggs
  | \.mypy_cache
  | \.pytest_cache
  | \__pycache__
  | build
  | dist
)/
'''
